### ISSUE TITLE
Validazione lato server

### ISSUE THREAD

**Issue by RiccardoAgatea** [RiccardoAgatea/uovoallacoque#24]
Bisogna validare i dati lato server nella registrazione.

**Comment by AkaiSara** [comment]
validation.php
- [x] Controllo password uguali
- [x] Nome ricetta: 1) controllo lughezza come js 2) controllo che non sia presente nel db
- [x] Email 1) che sia ben formato 2) non presente nel database
- [x] tempo {0, inf} (non deve essere float)
- [x] diffiicoltà

Immagine??
